full-trace: true
check-leaks: true
recursive: true
timeout: 10000
exit: true
global:
  # from testing NodeManager class
  - breakpointMethods
  - verbose
  - dryRun
  - params
spec:
  - dist/**/*.test.js
