version: 2.1

orbs:
  sixrs-gke: sixriversystems/sixrs-gke@3

jobs:
  setup:
    docker:
      - image: cimg/node:10.17.0
        environment:
          NODE_ENV: test
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package-lock.json"}}
            - dependency-cache-
      - run:
          name: Install node dependencies
          command: |
            npm ci
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run: npm run compile
      - persist_to_workspace:
          root: ./
          paths:
            - .
  publish:
    docker:
      - image: cimg/node:10.17.0
        environment:
          NODE_ENV: test
    steps:
      - attach_workspace:
          at: ./
      - sixrs-gke/run-release
      - sixrs-gke/publish-public-npm
  test:
    docker:
      - image: cimg/node:10.17.0
        environment:
          NODE_ENV: test
          MOCHA_OPTS: --reporter mocha-junit-reporter --reporter-options mochaFile=./reports/junit/mocha/mocha.xml
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: npm test
          command: |
            npm test
      - run:
          name: npm run coverage
          command: |
            npm run coverage
      - store_artifacts:
          path: coverage
      - store_artifacts:
          path: reports/junit/
      - store_test_results:
          path: reports/junit/

workflows:
  version: 2

  test_and_publish:
    jobs:
      - setup
      - test:
          requires:
            - setup
      - publish:
          context: 6rs-public-npm
          requires:
            - test
